spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DB}?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
#        show_sql: true
#    show-sql: true

#  cache:
#    type: redis
#
#  data:
#    redis:
#      host: localhost
#      port: 6379

# rabbitmq 설정
  rabbitmq:
    listener:
      simple:
        acknowledge-mode: none

    host: ${RABBITMQ_HOST} # RabbitMQ host ip
    port: 5672 # RabbitMQ port
    username: ${RABBITMQ_USERNAME} # RabbitMQ 웹 관리 콘솔 아이디
    password: ${RABBITMQ_PASSWORD} # RabbitMQ 웹 관리 콘솔 비밀번호

rabbitmq:
  submission:
    exchange:
      name: submission-exchange

    request:
      queue:
        name: submission-request-queue
      routing:
        key: submission-request-route

    result:
      queue:
        name: submission-result-queue
      routing:
        key: submission-result-route

management:
  endpoints:
    web:
      exposure:
        include: "*"

cloud:
  aws:
    s3:
      endpoint: http://localhost:9000   # MinIO API 주소
      bucket: sd_images                 # 위에서 만든 버킷 이름
    credentials:
      access-key: sd_admin            # MinIO Access Key
      secret-key: sd_password            # MinIO Secret Key
    region:
      static: us-east-1                 # AWS region처럼 지정 (MinIO는 의미 없음)
    stack:
      auto: false                       # CloudFormation 관련 설정, 꺼도 무방